- name: "Actualizando sistema"
  apt: update_cache=yes upgrade=yes

- name: "Pasando clave p√∫blica" 
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become: yes
